const data = {
  prefix_2: [
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "20 x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 20,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "21 x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 21,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "22 x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 22,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "23 x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 23,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "24 x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 24,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "25x xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 25,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "30 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 30,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "31 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 31,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "32 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 32,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "33 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 33,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "36x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 36,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "41x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 41,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "42x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 42,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "43x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 43,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "45x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 45,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "47x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 47,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "49x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 49,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "50 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 50,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "51 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 51,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "52 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 52,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "53 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 53,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "54 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 54,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "55 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 55,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "56 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 56,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "67x xxx - xxx",
      allocated_date: "8.3.2019",
      prefix: 67,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "68x xxx - xxx",
      allocated_date: "12.10.2018",
      prefix: 68,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "69x xxx - xxx",
      allocated_date: "9.3.2017",
      prefix: 69,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "73x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 73,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "76x xxx - xxx",
      allocated_date: "3.5.2016",
      prefix: 76,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "77x xxx - xxx",
      allocated_date: "1.10.2015",
      prefix: 77,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "78x xxx - xxx",
      allocated_date: "13.2.2015",
      prefix: 78,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "79x xxx - xxx",
      allocated_date: "11.4.2014",
      prefix: 79,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "83 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 83,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "84 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 84,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "85 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 85,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "86 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 86,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "87 x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 87,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "91x xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 91,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "95x xxx - xxx",
      allocated_date: "19.1.2017",
      prefix: 95,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "96x xxx - xxx",
      allocated_date: "8.1.2016",
      prefix: 96,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "97x xxx - xxx",
      allocated_date: "15.1.2015",
      prefix: 97,
      number_length: 9,
      prefix_length: 2,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "98x xxx - xxx",
      allocated_date: "12.7.2019",
      prefix: 98,
      number_length: 9,
      prefix_length: 2,
    },
  ],
  prefix_3: [
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "260 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 260,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "261 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 261,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "262 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 262,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "263 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 263,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "264 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 264,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "265 xxx – xxx",
      allocated_date: "24.3.2015",
      prefix: 265,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "266 xxx - xxx",
      allocated_date: "1.12.2018",
      prefix: 266,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "267 xxx - xxx",
      allocated_date: "1.2.2019",
      prefix: 267,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "268 xxx - xxx",
      allocated_date: "1.2.2019",
      prefix: 268,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "269 xxx - xxx",
      allocated_date: "1.4.2019",
      prefix: 269,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "349 0xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 349,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "400 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 400,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "401 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 401,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "402 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 402,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "403 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 403,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "404 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 404,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "405 xxx - xxx",
      allocated_date: "1.8.2019",
      prefix: 405,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "406 xxx - xxx",
      allocated_date: "1.7.2019",
      prefix: 406,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "407 xxx - xxx",
      allocated_date: "1.6.2019",
      prefix: 407,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "408 xxx - xxx",
      allocated_date: "1.5.2019",
      prefix: 408,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "409 xxx - xxx",
      allocated_date: "1.5.2019",
      prefix: 409,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "440 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 440,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "441 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 441,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "442 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 442,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "443 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 443,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "444 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 444,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "445 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 445,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "446 xxx - xxx",
      allocated_date: "1.4.2019",
      prefix: 446,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "447 xxx - xxx",
      allocated_date: "1.11.2018",
      prefix: 447,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "448 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 448,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "449 xxx - xxx",
      allocated_date: "24.3.2015",
      prefix: 449,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "650 xxx - xxx",
      allocated_date: "9.4.2020",
      prefix: 650,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "651 xxx - xxx",
      allocated_date: "22.10.2021",
      prefix: 651,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "652 xxx - xxx",
      allocated_date: "22.10.2021",
      prefix: 652,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "653 xxx - xxx",
      allocated_date: "6.1.2023",
      prefix: 653,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "660 xxx - xxx",
      allocated_date: "17.7.2019",
      prefix: 660,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "661 xxx - xxx",
      allocated_date: "17.7.2019",
      prefix: 661,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "662 xxx - xxx",
      allocated_date: "17.7.2019",
      prefix: 662,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "663 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 663,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "664 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 664,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "665 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 665,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "666 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 666,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "667 xxx - xxx",
      allocated_date: "2.1.2020",
      prefix: 667,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "668 xxx - xxx",
      allocated_date: "2.1.2020",
      prefix: 668,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Mytel",
      operator_name: "Telecom International Myanmar Co.,Ltd",
      country_code: 95,
      area_code: 9,
      subscriber_number: "669 xxx - xxx",
      allocated_date: "2.1.2020",
      prefix: 669,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "740 xxx - xxx",
      allocated_date: "9.4.2020",
      prefix: 740,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "750 xxx - xxx",
      allocated_date: "1.12.2017",
      prefix: 750,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "751 xxx - xxx",
      allocated_date: "1.12.2017",
      prefix: 751,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "752 xxx - xxx",
      allocated_date: "1.12.2017",
      prefix: 752,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "753 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 753,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "754 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 754,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "755 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 755,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "756 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 756,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "757 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 757,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "758 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 758,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Atom",
      operator_name: "ATOM Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "759 xxx - xxx",
      allocated_date: "3.6.2019",
      prefix: 759,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "880 xxx - xxx",
      allocated_date: "3.2.2020",
      prefix: 880,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "881 xxx - xxx",
      allocated_date: "3.2.2020",
      prefix: 881,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "882 xxx - xxx",
      allocated_date: "3.2.2020",
      prefix: 882,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "883 xxx - xxx",
      allocated_date: "3.2.2020",
      prefix: 883,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "884 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 884,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "885 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 885,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "886 xxx - xxx",
      allocated_date: "9.10.2019",
      prefix: 886,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "887 xxx - xxx",
      allocated_date: "1.8.2019",
      prefix: 887,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "888 xxx - xxx",
      allocated_date: "1.8.2019",
      prefix: 888,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "889 xxx - xxx",
      allocated_date: "1.8.2019",
      prefix: 889,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "890 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 890,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "891 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 891,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "892 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 892,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "893 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 893,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "894 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 894,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "895 xxx - xxx",
      allocated_date: "8.3.2018",
      prefix: 895,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "896 xxx - xxx",
      allocated_date: "31.3.2017",
      prefix: 896,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "897 xxx - xxx",
      allocated_date: "23.11.2017",
      prefix: 897,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "898 xxx - xxx",
      allocated_date: "23.11.2017",
      prefix: 898,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "MPT",
      operator_name: "Myanma Posts and Telecommunications",
      country_code: 95,
      area_code: 9,
      subscriber_number: "899 xxx - xxx",
      allocated_date: "23.11.2017",
      prefix: 899,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "940 xxx - xxx",
      allocated_date: "9.4.2020",
      prefix: 940,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "941 xxx - xxx",
      allocated_date: "6.8.2020",
      prefix: 941,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "942 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 942,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "943 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 943,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "944 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 944,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "945 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 945,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "946 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 946,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "947 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 947,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "948 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 948,
      number_length: 9,
      prefix_length: 3,
    },
    {
      operator_code: "Ooredoo",
      operator_name: "Ooredoo Myanmar Limited",
      country_code: 95,
      area_code: 9,
      subscriber_number: "949 xxx - xxx",
      allocated_date: "30.6.2021",
      prefix: 949,
      number_length: 9,
      prefix_length: 3,
    },
  ],
  prefix_4: [
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "3400 xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 3400,
      number_length: 9,
      prefix_length: 4,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "3401 xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 3401,
      number_length: 9,
      prefix_length: 4,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "3402 xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 3402,
      number_length: 9,
      prefix_length: 4,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "3460 xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 3460,
      number_length: 9,
      prefix_length: 4,
    },
    {
      operator_code: "MecTel",
      operator_name: "Myanmar Economic Corporation",
      country_code: 95,
      area_code: 9,
      subscriber_number: "3461 xx - xxx",
      allocated_date: "29.3.2016",
      prefix: 3461,
      number_length: 9,
      prefix_length: 4,
    },
  ],
};

const myanmar_numbers = [
  "၀",
  "၁",
  "၂",
  "၃",
  "၄",
  "၅",
  "၆",
  "၇",
  "၈",
  "၉",
  "၁၀",
];

function Validator(props) {

  if (typeof props !== "string" && typeof props !== "number") return null;

  // change to number
  const number = parseInt(
    `${props}`
      .split("")
      .map((char) =>
        myanmar_numbers.includes(char)
          ? myanmar_numbers.findIndex((element) => element === char)
          : char
      )
      .toString()
      .replaceAll(/[\s,]/g, "")
  );

  // if not mobile number code xxx-xxx-xxx or with country code 95-09-xxx-xxx-xxx
  if (`${number}`.length < 9 || `${number}`.length > 13) return null;

  // remove country code
  let mobile = `${number}`.startsWith("95") ? `${number}`.slice(2) : `${number}`;

  // after remove country code number length must be 11 ( with area code 09 ) or 9
  if (mobile.length < 9 || mobile.length > 11) return null;

  // remove area code if type 09
  if (mobile.startsWith("09")) {
    mobile = `${mobile}`.slice(2);
  }

  // remove area code if type 9
  if (mobile.length === 10 && mobile.startsWith("9")) {
    mobile = `${mobile}`.slice(1);
  }

  // after remove country and area code number length must be 9 for mobile
  if (mobile.length !== 9) return null;

  let info = null;
  // search mobile data
  // find in prefix 2
  info = data.prefix_2.find(
    (value) => value.prefix === parseInt(mobile.slice(0, 2))
  );

  if (info)
    return {
      number: mobile,
      operator_code: info.operator_code,
      operator_name: info.operator_name,
    };

  // find in prefix 3
  info = data.prefix_3.find(
    (value) => value.prefix === parseInt(mobile.slice(0, 3))
  );

  if (info)
    return {
      number: mobile,
      operator_code: info.operator_code,
      operator_name: info.operator_name,
    };

  // find in prefix 4
  info = data.prefix_4.find(
    (value) => value.prefix === parseInt(mobile.slice(0, 4))
  );

  return info
    ? {
        number: mobile,
        operator_code: info.operator_code,
        operator_name: info.operator_name,
      }
    : null;
}

module.exports = Validator;
